apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - talend-registry
  containers:
    - name: python3
      image: jenkinsxio/builder-python3
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      resources:
        requests:
          memory: "1G"
          cpu: "1"
        limits:
          memory: "2G"
          cpu: "3"
    - name: maven3
      image: jenkinsxio/builder-maven
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      resources:
        requests:
          memory: "1G"
          cpu: "1"
        limits:
          memory: "2G"
          cpu: "3"
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
