apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: jenkinsxio/builder-python2
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "128M"
          cpu: "1"
        limits:
          memory: "1G"
          cpu: "3"